### ISSUE TITLE
Tags releases should be managed and documented clearly

### ISSUE THREAD

**Issue by AbdallaDalleh** [motorapp/Galil-3-0#19]
Few weeks ago, we installed a new Galil IOC with the latest Galil driver from GitHub, motors were moving OK but the DMC always giving controller start error because of an issue with the generated DMC code. After deep investigation, it turns out that in the "latest" version, which has been 3.6 for a while, the `GalilCreateAxis` IOC shell function no longer has the `limits_as_home` argument and our setup, assuming it is still there, would pass 1 to the motor interlock digital port argument, therefore generating extra DMC code for stopping the motors in case of a digital port interlock.

I don't see anywhere where this is documented or at least mentioned, the release management for the Galil EPICS driver is really confusing because of two points:

- The driver has been in version 3.6 for a while now but it has been updated on the same tag many times, this is very confusing.
- Release notes for each update is not clear enough.

We really hope this to be taken care of in future releases or updates.

**Comment by motorapp** [comment]
Hi AbdallaDalleh,
Sure, I understand.  Will do.
Just so you know the change you are referring to appears in the change_log.txt as the line below.
Moved "limits as home" option to motor extras with PV $(P)$M)ULAH_CMD/$(P)$M)ULAH_STATUS
The PV's mentioned in the change log (above line) appear on the motor extras screen.
Apologies for any inconvenience. 
Kind regards,
Mark
